version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    env_file:  
      - ./server/.env
    environment:
      - DOCKER_ENV=true 
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
